x3: configs: permissions: Add missing permissions for Launcher3 & Systemui
java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions allowlist: {com.android.launcher3 (/system_ext/priv-app/Launcher3QuickStep): android.permission.MEDIA_CONTENT_CONTROL, com.android.launcher3 (/system_ext/priv-app/Launcher3QuickStep): android.permission.PACKAGE_USAGE_STATS, com.android.launcher3 (/system_ext/priv-app/Launcher3QuickStep): android.permission.MANAGE_USERS, com.android.launcher3 (/system_ext/priv-app/Launcher3QuickStep): android.permission.FORCE_STOP_PACKAGES, com.android.systemui (/system_ext/priv-app/SystemUI): android.permission.WRITE_APN_SETTINGS}

* Also its makes bootloop

Signed-off-by: akmacc <arumugamguna7058@gmail.com>